#ifndef __PINOUT_H__
#define __PINOUT_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <fsl_common.h>
#include <fsl_gpio.h>
#include <fsl_port.h>

/* External UART */
#define UART_BASE UART1
#define UART_BAUD_RATE 2400U
#define UART_XON 0x11U
#define UART_XOFF 0x13U

#define UART_TX_PIN 0U
#define UART_TX_PORT PORTE

#define UART_RX_PIN 1U
#define UART_RX_PORT PORTE

/* Built-int LED*/

#define BUILTIN_LED_ON 0
#define BUILTIN_LED_OFF 1

// RED
#define BUILTIN_LED_R_PIN 29U
#define BUILTIN_LED_R_GPIO GPIOE
#define BUILTIN_LED_R_PORT PORTE

// GREEN
#define BUILTIN_LED_G_PIN 5U
#define BUILTIN_LED_G_GPIO GPIOD
#define BUILTIN_LED_G_PORT PORTD

/* Seven segments display */

// SECTIONS
#define DISPLAY_SECTION_ON 0
#define DISPLAY_SECTION_OFF 1

#define DISPLAY_SECTION_1_PIN 3U
#define DISPLAY_SECTION_1_GPIO GPIOD
#define DISPLAY_SECTION_1_PORT PORTD

#define DISPLAY_SECTION_2_PIN 12U
#define DISPLAY_SECTION_2_GPIO GPIOA
#define DISPLAY_SECTION_2_PORT PORTA

#define DISPLAY_SECTION_3_PIN 4U
#define DISPLAY_SECTION_3_GPIO GPIOA
#define DISPLAY_SECTION_3_PORT PORTA

// SEGMENTS
#define DISPLAY_SEGMENT_ON 0
#define DISPLAY_SEGMENT_OFF 1

#define DISPLAY_SEGMENT_A_PIN 13U
#define DISPLAY_SEGMENT_A_GPIO GPIOA
#define DISPLAY_SEGMENT_A_PORT PORTA

#define DISPLAY_SEGMENT_B_PIN 2U
#define DISPLAY_SEGMENT_B_GPIO GPIOD
#define DISPLAY_SEGMENT_B_PORT PORTD

#define DISPLAY_SEGMENT_C_PIN 13U
#define DISPLAY_SEGMENT_C_GPIO GPIOC
#define DISPLAY_SEGMENT_C_PORT PORTC

#define DISPLAY_SEGMENT_D_PIN 16U
#define DISPLAY_SEGMENT_D_GPIO GPIOC
#define DISPLAY_SEGMENT_D_PORT PORTC

#define DISPLAY_SEGMENT_E_PIN 7U
#define DISPLAY_SEGMENT_E_GPIO GPIOA
#define DISPLAY_SEGMENT_E_PORT PORTA

#define DISPLAY_SEGMENT_F_PIN 4U
#define DISPLAY_SEGMENT_F_GPIO GPIOD
#define DISPLAY_SEGMENT_F_PORT PORTD

#define DISPLAY_SEGMENT_G_PIN 6U
#define DISPLAY_SEGMENT_G_GPIO GPIOA
#define DISPLAY_SEGMENT_G_PORT PORTA

#ifdef __cplusplus
}
#endif

#endif
